#ifndef VM_SEGMENT_INCLUDE_DEFINE_CONSTANT_H
#define VM_SEGMENT_INCLUDE_DEFINE_CONSTANT_H

typedef enum{

    VM_MENU_OPTION_NEW_PROCESSES = 1,
    VM_MENU_OPTION_HALT_PROCESSES,
    VM_MENU_OPTION_PRINT_ALL_PROCESSES,
    VM_MENU_OPTION_PRINT_ALL_SEGMENT_TABLE_ITEMS
}VM_MENU_OPTION;


#endif


