#ifndef INCLUDE_DEFINE_CONSTANT_H
#define INCLUDE_DEFINE_CONSTANT_H

#define MEMORY_UNIT_COUNT 1000; // 内存单元个数

#define VM_TYPE_PAGE 1;
#define VM_TYPE_SEGMENT 2;
#define VM_TYPE_SEGMENT_PAGE 3;

#define VM_MENU_OPTION_PRINT_ALL_PROCESSES 1;
#define VM_MENU_OPTION_NEW_PROCESSES 2;
#define VM_MENU_OPTION_HALT_PROCESSES 3;

#endif